vich_uploader:
    db_driver: orm

    mappings:
        marker_photo:
            uri_prefix: /upload/marker_photo
            upload_destination: '%kernel.project_dir%/public/upload/marker_photo'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
